jobs:
    include:
        -
            stage: test
            env: Type='virus scan'
            script:
                - sudo apt-get install clamav -y
                - sudo freshclam
                - clamscan --quiet -r ./
        -
            stage: test
            env: Type='unit test'
            language: csharp
            dotnet: 2.1.3
            mono: latest
            before_script:
                - nvm install 8
                - npm install -g codecov
            script:
                - npm i
                - dotnet restore
                - dotnet fable npm-run coverage
            after_success:
                - codecov
        -
            stage: deploy
            language: csharp
            dotnet: 2.1.3
            mono: latest
            if: branch =~ ^v\d+\.\d+\.\d+$
            script:
                - cd fable
                - dotnet pack
                - cd bin/Debug/netstandard2.0
                - dotnet nuget push *.nupkg -k $NUGET_KEY
